# Use root/example as user/password credentials
version: '3.1'

services:
  news-app:
    build: .
    container_name: news-app
    ports:
      -  8000:8000
    depends_on:
      -  db
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: brickDBmaria9
      MARIADB_PASSWORD: brickDBmaria9
    ports:
      - 3306:3306